### ISSUE TITLE
Is there a limit to the number of point cloud points that used as prompts?

### ISSUE THREAD

**Issue by hm123450** [theodorakontogianni/InterObject3D#6]
Hello, Thank you for great your work very much. It helps me a lot. I would like to ask, if I already have a complete 3D scene graph as well as some processed sparse point clouds for prompts, Is there a limit to the number of point cloud points for interactive prompts? The processed sparse point clouds may be a lot.

**Comment by theodorakontogianni** [comment]
Thank you for your kind words! I’m glad the work has been helpful to you. During training, click prompts are selected randomly on the object (positive clicks) and at random points close to the object (hard negatives). During testing, the first click is placed on the object, and subsequent clicks are placed in the center of the largest error region. But the setup can be modified to fit your initialization policy (graph nodes or samples).

In theory, there is no strict limitation on the number of interactive clicks. However, the number of points in the point cloud is limited by the available GPU memory. If your scene contains a very large number of points, you may encounter memory constraints. The best approach is probably to crop regions around the objects of interest or sparsify the point cloud.

I hope it answers the question! Feel free to reach out if you have further questions or need additional clarification.

**Comment by hm123450** [comment]
> Thank you for your kind words! I’m glad the work has been helpful to you. During training, click prompts are selected randomly on the object (positive clicks) and at random points close to the object (hard negatives). During testing, the first click is placed on the object, and subsequent clicks are placed in the center of the largest error region. But the setup can be modified to fit your initialization policy (graph nodes or samples).
> 
> In theory, there is no strict limitation on the number of interactive clicks. However, the number of points in the point cloud is limited by the available GPU memory. If your scene contains a very large number of points, you may encounter memory constraints. The best approach is probably to crop regions around the objects of interest or sparsify the point cloud.
> 
> I hope it answers the question! Feel free to reach out if you have further questions or need additional clarification.

Wow, I really appreciate your quick responses. I think I can do some extraction and filtering to reduce the number of prompt points. I have another small question: Are there any methods to obtain 3D masks without interactive clicking? As I mentioned earlier, I have already obtained some prompt points of the object, and I want to know if it is possible to get a 3D mask without manually clicking on the GUI?

**Comment by theodorakontogianni** [comment]
If you do not want to interact, even with simulated clicks (no GUI clicking, just a simulated policy based on some initialization and statistics) you can maybe check methods like MASK3D that sample points of potential object instances (you can possibly use your sampling) and give you the instance masks but without the option to correct if a mask is not to your liking and might have some issues if the objects you want to segment are not part of your training set! Possibly some 3D methods that use SAM might be an option.

**Comment by hm123450** [comment]
> If you do want to interact, even with simulated clicks (no GUI clicking, just a simulated policy based on some initialization and statistics) you can maybe check methods like MASK3D that sample points of potential object instances (you can possibly use your sampling) and give you the instance masks but without the option to correct if a mask is not to your liking and might have some issues if the objects you want to segment are not part of your training set! Possibly some 3D methods that use SAM might be an option.

Thank you very much! You are so friendly and kind. I will try out and find what fits most.
